apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoint-bucket-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 64Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcsfuse-sc # dummy storage class
  claimRef:
    namespace: default
    name: checkpoint-bucket-pvc
  mountOptions:
    - metadata-cache:ttl-secs:-1
    - metadata-cache:negative-ttl-secs:0
    - metadata-cache:stat-cache-max-size-mb:-1
    - metadata-cache:type-cache-max-size-mb:-1
    - file-cache:enable-parallel-downloads:false
    - file-system:kernel-list-cache-ttl-secs:0
    - write:enable-streaming-writes:true
    - file-system:precondition-errors:false
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: checkpoint-bucket-name # Update with your checkpoint bucket name
    volumeAttributes:
      gcsfuseMetadataPrefetchOnMount: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoint-bucket-pvc
  namespace: defaultls
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: checkpoint-bucket-pv
  storageClassName: gcsfuse-sc # dummy storage class
